route.scala
=> #1: scala.meta.syntatic.Token does not exist (closes #1)

extractors.scala, intermediate.scala, main.scala, route.scala, src/test/scala/extractors/Fixture.scala, src/test/scala/extractors/RouteSuite.scala
=> Support route names and overrides at the extractor level (first step to #7)

route.scala
refer to
https://github.com/scalameta/scalameta/commit/8cf487b842ca0e69c05f83b55247a2331c95c730
Unit tests
=> scala.meta literals have been merged in a single case class

extractors.scala, fixture/models.scala, intermediate.scala, model.scala, src/test/scala/extractors/ModelSuite.scala, src/test/scala/extractors/RouteSuite.scala
=> #11: Extract `case enum`s (closes #11)

annotations/build.sbt, annotations/package.scala, annotations/src/test/scala/package.scala, build.sbt, fixture/routes.scala, project/Build.scala, route.scala
=> Provide a minimal dependency with metarpheus marker annotations

annotations/build.sbt, annotations/project/plugins.sbt, build.sbt, project/plugins.sbt
=> #21: Make projects publishable on bintray (closes #21)

route.scala
Issue #19 
Tested locally removing the braces from the fixture.
Adding a test looked like a lot of work, given the current structure of the fixtures, but if there's an easy way, let me know, @utaal
=> #19: MatchError while parsing a router (closes #19)

fixture/models.scala, intermediate.scala, src/test/scala/extractors/ApiSuite.scala, src/test/scala/extractors/Common.scala, src/test/scala/extractors/ModelSuite.scala, src/test/scala/extractors/RouteSuite.scala
=> #24: Models are not extracted recursively (closes #24)

extractor/route.scala
=> #26: Sometimes ctrl method is not eta expanded (closes #26)

extractor/extractors.scala, extractor/fixture/sources/routes.scala, extractor/route.scala, extractor/src/test/scala/extractors/RouteSuite.scala
=> #29: Allow providing names for path params (closes #29)

extractor/extractors.scala, extractor/main.scala, extractor/model.scala, extractor/route.scala, extractor/src/test/scala/extractors/ApiSuite.scala, extractor/src/test/scala/extractors/ModelSuite.scala, extractor/src/test/scala/extractors/RouteSuite.scala
=> #31: Integrate new changes in scala meta Tree api (closes #31)

extractor/fixture/sources/routes.scala, extractor/route.scala, extractor/src/test/scala/extractors/RouteSuite.scala
=> #33: Simple spray parameters are not supported (closes #33)

extractor/extractors.scala, extractor/fixture/sources/models.scala, extractor/model.scala, extractor/route.scala, extractor/src/test/scala/extractors/ModelSuite.scala
=> #39: [description] `description` should be optional (closes #39)

extractor/extractors.scala, extractor/model.scala
Issue #41
hot fix, tests are now running
=> #41: Fix build, implicit dialect missing in tokens (closes #41)

extractor/extractors.scala, extractor/fixture/sources/models.scala, extractor/model.scala, extractor/src/test/scala/extractors/ModelSuite.scala
=> #44: Support new syntax of caseenum (closes #44)

extractor/config.scala, extractor/fixture/sources/models.scala, extractor/intermediate.scala, extractor/main.scala, extractor/src/test/scala/extractors/ApiSuite.scala, extractor/src/test/scala/extractors/Common.scala, extractor/src/test/scala/extractors/ModelSuite.scala
Issue #49
- updated unit tests
- tested on bobafett
=> #49: Allow inclusion of custom models in the build (closes #49)

extractor/extractors.scala, extractor/fixture/sources/models.scala, extractor/src/test/scala/extractors/ModelSuite.scala
=> #53: Model extractor can't parse fully qualified types (closes #53)

.drone.yml, .hophoprc, build.sbt, core/main.scala, core/src/test/scala/MainSuite.scala, core/src/test/scala/fixtures.scala
Closes #55
tested locally with banksealer
=> #55: Trailing arguments accept only directories (closes #55)

core/shared/src/main/scala/io.buildo.metarpheus/core/extractors/controller.scala, core/shared/src/test/resources/fixtures/controllers.scala
=> #66: Fix auth handling (closes #66)

core/shared/src/main/scala/io.buildo.metarpheus/core/extractors/controller.scala, core/shared/src/test/resources/fixtures/controllers.scala, core/shared/src/test/resources/fixtures/models.scala, core/shared/src/test/scala/io.buildo.metarpheus/core/extractors/ApiSuite.scala, core/shared/src/test/scala/io.buildo.metarpheus/core/extractors/ModelSuite.scala
=> #71: Allow to ignore routes (closes #71)

core/shared/src/main/scala/io.buildo.metarpheus/core/extractors/controller.scala, core/shared/src/test/resources/fixtures/controllers.scala, core/shared/src/test/scala/io.buildo.metarpheus/core/extractors/ControllerSuite.scala
Closes #74
tested locally
> A Test Plan is used to show what you tested to make sure your code works fine. You should write here all that you did to test, and provide some results of your testing.
> These results can be screenshots, query results, or even just pointers to unit tests that successfully passed.
> At times not everything can be tested, and writing what hasn't been tested is just as important as writing what has been tested.
> An example of partial test is a field displaying 4 possible values. If 3 values are tested, with screenshots, and 1 is not, then it should be mentioned here.
=> #74: Add support for tagless final syntax (closes #74)

.scalafmt.conf, build.sbt, core/shared/src/main/scala/io.buildo.metarpheus/core/extractors/controller.scala, core/shared/src/main/scala/io.buildo.metarpheus/core/extractors/model.scala, core/shared/src/test/resources/fixtures/models.scala, core/shared/src/test/scala/io.buildo.metarpheus/core/extractors/ApiSuite.scala, core/shared/src/test/scala/io.buildo.metarpheus/core/extractors/ControllerSuite.scala, core/shared/src/test/scala/io.buildo.metarpheus/core/extractors/ModelSuite.scala
Closes #76
> A Test Plan is used to show what you tested to make sure your code works fine. You should write here all that you did to test, and provide some results of your testing.
> These results can be screenshots, query results, or even just pointers to unit tests that successfully passed.}
> At times not everything can be tested, and writing what hasn't been tested is just as important as writing what has been tested.
> An example of partial test is a field displaying 4 possible values. If 3 values are tested, with screenshots, and 1 is not, then it should be mentioned here.}
=> #76: Metarpheus is broken with trailing commans (closes #76)
